### ISSUE TITLE
wifi traffic

### ISSUE THREAD

**Issue by QUEST2179** [TobiasHeOl/kasearch#6]
Dear Developer,

I downloaded oasdb_small to my computer and tried to run search locally, but noticed there is a heavy wifi traffic. Is it normal? the search is done in a remote server or in a local computer? Thanks!

**Comment by TobiasHeOl** [comment]
Hello! The actual search is done locally against the used pre-processed dataset (in your case oasdb_small), however; to extract the metadata for the N sequences with highest identity, the default is to extract it from the online OAS version hosted by OPIG (in order to keep the pre-processed datasets small, they do not include metadata). If you are returning a lot of sequences (large "keep_best_n"), this step might cause some heavy wifi traffic. 

We understand that you might want to perform this search fully locally, so you also have the option of downloading OAS (currently ~1.3T) and extracting metadata from this local version. This allows you to run kasearch offline and most likely also speed up the meta extraction part. To use a local OAS, you need to set the argument "local_oas_path='/path/to/local/oas/'" (please see example 4 in README).

I hope this answered your question! All the best,
Tobias

**Comment by QUEST2179** [comment]
Very helpful, thank you so much for explanation, Tobias.
